Improve documentation on group queries
sgarciac/fuego pull request #82
Opened 2022-10-19 21:53 UTC by clarityflowers

I had to dig through to find the original commit + test case for this feature to figure out how it worked. I figured I'd save future people the time and add "subcollection" as term to search for and an example of usage!

2022-10-19 23:16 UTC, sgarciac requested changes
Thanks! I tried to reword it a bit to make it clearer (in my opinion), let me know what you think.  I don't want it to make it sound as if you need group queries to query a single subcollection.

2022-10-19 23:16 UTC, sgarciac commented on README.md
> +#### Group queries (subcollections)
```suggestion
#### Group queries
```

2022-10-19 23:16 UTC, sgarciac commented on README.md
> +queries](https://firebase.google.com/docs/firestore/query-data/queries) to query subcollections by using
```suggestion
queries](https://firebase.google.com/docs/firestore/query-data/queries) to query all the subcollections sharing a common ID by using
```

2022-10-20 19:59 UTC, clarityflowers commented
Those changes seem good!

2022-10-26 13:09 UTC, merged